site_name: RAHA
nav:
  - Home: index.md
  - The team: about.md
  - Design: design.md
  - 3D Visualizations: 3D_Visualizations.md
  - Presentations: presentations.md
  - Other: other.md
theme:
  name: material
  logo: img/logo.png
  palette:
    primary: brown
  font:
    text: Maven Pro